apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: todo-app-pvclaim
      containers:
        - name: todo-backend
          image: todo-backend:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/files
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: PORT
            - name: IMAGE_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: IMAGE_FILE_PATH
            - name: REQUEST_IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: REQUEST_IMAGE_URL
            - name: TIME_TEN_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: TIME_TEN_SECONDS
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-configmap
                  key: DATABASE_URL
              
