apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: log-writer
          image: log_writer:latest
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
          imagePullPolicy: IfNotPresent
        - name: log-reader
          image: log_reader:latest
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
          imagePullPolicy: IfNotPresent
       
